version: 2
jobs:
  build:
    working_directory: ~/ionic/
    docker:
      - image: node:8
    branches:
      ignore:
        - core
    steps:
      - checkout
      - restore_cache:
         key: ionic-docs
      - run:
         name: Prepare ionic-site repo
         command: npm --prefix packages/core/ run ci-prep
      - save_cache:
         key: ionic-docs
         paths:
         - ~/ionic-docs/
      - restore_cache:
         key: node_modules_{{ checksum "package.json" }}
      - run:
         name: Install monorepo node modules
         command: npm i
      - save_cache:
         key: node_modules_{{ checksum "package.json" }}
         paths:
         - ~/ionic/node_modules/
      - restore_cache:
         key: node_modules_{{ checksum "packages/core/package.json" }}
      - run:
         name: Install core node modules
         command: npm --prefix packages/core/ i
      - save_cache:
         key: node_modules_{{ checksum "packages/core/package.json" }}
         paths:
         - ~/ionic/packages/core/node_modules/
      - run:
          name: Validate
          command: npm --prefix packages/core/ run validate
      - add_ssh_keys
      - deploy:
          name: Update docs
          command: |
            if [ "${CIRCLE_BRANCH}" == "core-ci" ]; then
              npm --prefix packages/core/ run validate
            else
              echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
            fi
